# Default Configuration for Image Quality Fusion Training

# Model Configuration
model:
  type: "deep"  # Options: deep, weighted, ensemble
  hidden_dim: 256
  dropout_rate: 0.3
  output_range: [1.0, 10.0]

# Training Configuration  
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 15

# Data Configuration
data:
  train_ratio: 0.8
  val_ratio: 0.15
  test_ratio: 0.05
  random_state: 42

# Feature Extraction
features:
  clip_model: "ViT-B-32"  # Options: ViT-B-32, ViT-L-14
  aesthetic_model: "laion_linear"  # Options: laion_linear, christophschuhmann_mlp
  force_recompute: false

# System Configuration
system:
  device: "auto"  # Options: auto, cpu, cuda, mps
  num_workers: 2